#ifndef CONTROLLER_INPUT_CONFIG_H
#define CONTROLLER_INPUT_CONFIG_H

#include "main.h"

#ifndef CONTROLLER_INPUT_SOURCE_NODE_ID
#define CONTROLLER_INPUT_SOURCE_NODE_ID 0U
#endif

#ifndef CONTROLLER_BUTTON_1_ID
#define CONTROLLER_BUTTON_1_ID 1U
#endif

#ifndef CONTROLLER_BUTTON_1_GPIO_Port
#define CONTROLLER_BUTTON_1_GPIO_Port GPIOA
#endif

#ifndef CONTROLLER_BUTTON_1_Pin
#define CONTROLLER_BUTTON_1_Pin GPIO_PIN_0
#endif

#ifndef CONTROLLER_BUTTON_1_PULL_MODE
#define CONTROLLER_BUTTON_1_PULL_MODE GPIO_PULLUP
#endif

#ifndef CONTROLLER_BUTTON_1_ACTIVE_STATE
#define CONTROLLER_BUTTON_1_ACTIVE_STATE GPIO_PIN_RESET
#endif

#ifndef CONTROLLER_BUTTON_DEBOUNCE_MS
#define CONTROLLER_BUTTON_DEBOUNCE_MS 40U
#endif

#endif
