[platformio]
default_envs = controller, client

[env]
platform = ststm32@~19.5.0
framework = stm32cube
board = marine_stm32f070c6tx
build_type = debug
upload_protocol = stlink
debug_tool = stlink
debug_init_break = tbreak main
monitor_speed = 115200
board_build.ldscript = ldscripts/STM32F070C6Tx_FLASH.ld
board_build.stm32cube.custom_config_header = yes
build_flags =
  -DUSE_HAL_DRIVER
  -I config/stm32
  -I include

[env:controller]
build_flags =
  ${env.build_flags}
  -I include/controller
build_src_filter =
  -<*>
  +<controller/>
  +<controller/**>

[env:client]
build_flags =
  ${env.build_flags}
  -I include/client
build_src_filter =
  -<*>
  +<client/>
  +<client/**>
